### ISSUE TITLE
|*| from master branch slower than in massiv-0.2.8.0

### ISSUE THREAD

**Issue by Magalame** [lehins/massiv#78] opened 2019-06-24 10:31 UTC
Hi!

First of all I'm really impressed by your work! 
I've noted something when running [some benchmarks](https://github.com/Magalame/fastest-matrices). I usually set the packages to be fetched directly from the last github commit that I know off, but I had forgotten to do so for `massiv` , as I had just recently added it to the benchmarks.
When I ended up switching for the last commit, `|*|` suddenly became slower.
On my machine, for 100*100 matrices, I get:

- for 2.8.0 (the `massiv` version packaged with lts13.22) : ~1.5 ms
- for master: ~2.4 ms
 
(60% slowdown)

---
EDIT:
After running some more tests the change seems to happen between 2.8 and 3.0. I couldn't test for 2.8.1 since github doesn't seem to recognize this tag

**Comment by lehins** [comment] 2019-06-24 10:59
@Magalame Thank you for this report and for working on the matrices benchmarks.

Quite a bit has changed from 2.x to 3.x in massiv, so it won't be trivial to figure out where regression is coming from, but I will try to narrow it down. Also current implementation of matrix multiplication isn't optimal, after checking out your approach in `dense-linear-algebra`, I thought that it can be improved in `massiv`.

**Comment by Magalame** [comment] 2019-06-24 11:16
You're very welcome!

I looked around a bit, the only observation I could really make is that `A.foldlS (+) 0 $ A.zipWith (*)` has exactly the same performances in both version, so probably not the culprit.

Also do you mind detailing a bit about what you mean regarding the current implementation?

**Comment by lehins** [comment] 2019-06-24 12:37
I just gave it a shot and did see the regression from `0.2.8.0` to `master` (`0.3.5.0`), but the difference wasn't as drastic, only around 10%
Nevertheless it is still a slowdown and it is worth investigating.

```
benchmarking Massiv/repeated multiplication
time                 3.328 ms   (3.313 ms .. 3.351 ms)
                     1.000 R²   (0.999 R² .. 1.000 R²)
mean                 3.328 ms   (3.322 ms .. 3.345 ms)
std dev              31.54 μs   (20.49 μs .. 51.40 μs)

benchmarking Massiv/multiplication
time                 1.106 ms   (1.102 ms .. 1.109 ms)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 1.107 ms   (1.105 ms .. 1.110 ms)
std dev              8.521 μs   (6.592 μs .. 11.40 μs)
```
 vs massiv-0.2.8.0:

```
benchmarking Massiv/repeated multiplication
time                 2.987 ms   (2.962 ms .. 3.011 ms)
                     0.999 R²   (0.998 R² .. 1.000 R²)
mean                 3.027 ms   (3.006 ms .. 3.061 ms)
std dev              82.15 μs   (61.22 μs .. 124.4 μs)
variance introduced by outliers: 13% (moderately inflated)

benchmarking Massiv/multiplication
time                 1.048 ms   (1.039 ms .. 1.061 ms)
                     0.999 R²   (0.999 R² .. 0.999 R²)
mean                 1.055 ms   (1.049 ms .. 1.062 ms)
std dev              21.33 μs   (18.30 μs .. 25.40 μs)
```

**Comment by Magalame** [comment] 2019-06-24 13:18
I made a branch with a somewhat cleaner `Runtime.hs` : https://github.com/Magalame/fastest-matrices/tree/massiv-mul

To change from `0.2.8.0` to `0.3.5.0` you can just comment/uncomment the `commit` lines in `stack.yaml`, along with the `scheduler` version.

**Comment by Magalame** [comment] 2019-06-24 14:07
I think I've boiled it down to this line: `deepseq vMA $ deepseq aMA $ deepseq bMA $ return ()`

When we `deepseq` the arrays, they seem to yield to 60% decrease in performance I observed.

**Comment by lehins** [comment] 2019-06-24 15:11
Yes, this would explain such a serious slowdown. That is the reason why I always try to use `env` from `criterion`. I've added a fix for it in Magalame/fastest-matrices#3 :
> I think I've boiled it down to this line: deepseq vMA $ deepseq aMA $ deepseq bMA $ return ()

I was working on my own benchmarks for the matrix multiplication and I was getting a factor of x2 slower runtime for `massiv` comparing to `dense-linear-algebra` (`Statistics.Matrix.Fast.multiply`), which lead me to believe that I could improve current massiv implementation. But now I realized that the implementation in the `dense-linear-algebra` had a subtle bug, which has a fix in this PR: DataHaskell/dh-core#63 
> Also do you mind detailing a bit about what you mean regarding the current implementation?

I'll keep this issue open for a bit, so I can try to find where the 10% slowdown is coming from, when comparing to 0.2.x version.

**Comment by Magalame** [comment] 2019-06-24 15:43
Do you mind explaining what is the effect of using `env` here?

Also thanks for the PRs!

**Comment by lehins** [comment] 2019-06-24 15:59
One of the things [`env`](https://hackage.haskell.org/package/criterion-1.5.5.0/docs/Criterion.html#v:env) does is `deepseq` the values returned by the supplied action, so the effect of `deepseq vMA $ deepseq aMA $ deepseq bMA $ return ()` will be achieved by the `env`. Checkout the doc to see why else `env` is good to use.

**Comment by lehins** [comment] 2019-06-28 10:50
Running the benchmarks few more times on both versions, yielded nearly identical performance between massiv-0.2.8 ad massiv-0.3.5, so I can safely close this ticket

**Closed by lehins** 2019-06-28 10:50 UTC
