### ISSUE TITLE
GPU backend

### ISSUE THREAD

**Issue by masterdezign** [lehins/massiv#79] opened 2019-06-30 11:45 UTC
Hi Alexey!

I have enjoyed building [neural networks with massiv](http://penkovsky.com/post/neural-networks-4/).

Any plans to add the GPU backend?

**Comment by lehins** [comment] 2019-06-30 15:09
Hi Bogdan!

This is a pretty cool blog post and nice work Neural Networks! 

Unfortunately massiv was not designed with swappable backends in mind. I was striking for a pure, efficient Haskell implementation of array processing library with automatic parallelization on CPU. Adding support for things like CUDA or LLVM was never really in my plans, especially since there is already a defacto library in Haskell [`accelerate`](https://www.stackage.org/package/accelerate) that was designed specifically for that.

I am gonna close this ticket as a won't fix, but if anyone is willing to start a separate package `massiv-gpu` in this repo, that sort of mimics the current library API, I don't think I would be against it.

**Closed by lehins** 2019-06-30 15:09 UTC

**Comment by masterdezign** [comment] 2019-06-30 15:52
Thank you for the update. Indeed, the problem of having an additional GPU backend is not trivial.
Last year, there was [an attempt](https://github.com/ajknapp/accelerate-ad)
to combine `accelerate` with automatic differentiation,
which eventually [failed](https://ajknapp.github.io/2018/08/14/notomatic-differentiation.html).
The main reason was the strictness of the library that was initially designed for
[software correctness](http://www.acceleratehs.org/publications.html#type-safe-runtime-code-generation-accelerate-to-llvm).

Indeed, it could be not such a bad idea having a GPU library with massiv API, provided
that it could support (parallel) automatic differentiation.
